### ISSUE TITLE
urls not blocked

### ISSUE THREAD

**Issue by leonardosedevic** [stop-it/firefox-addon#4]
old blocked urls from my database are no more blocked like "xnxx.com" by the add-on version 1.9.0

**Comment by ondrejd** [comment]
See this my question - [https://discourse.mozilla-community.org/t/add-ons-written-using-jpm/2558](https://discourse.mozilla-community.org/t/add-ons-written-using-jpm/2558) - this is what is behind this issue not the missing URLs...

It will be solved either I will write own `bootstrap.js` file or we just wait for the newer Firefox version...

**Comment by leonardosedevic** [comment]
oh i see :p

**Comment by leonardosedevic** [comment]
Hello 
any news? :D

Leonardo SedevcicDeveloper ofhttp://stop-it.be/
